version: "3"

services:
    mediawiki:
        image: 741856792944.dkr.ecr.ap-south-1.amazonaws.com/mediawiki-2:latest
        container_name: mediawiki
        restart: always
        ports:
            - "8000:80"
        networks:
            - wikinetwork
    db:
        image: 741856792944.dkr.ecr.ap-south-1.amazonaws.com/mariadb:latest
        container_name: db
        restart: always
        env_file: .env
        environment:
            - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
            - MARIADB_DATABASE=$MARIADB_DATABASE
        ports:
            - "33060:3306"
        networks:
            - wikinetwork

networks:
    wikinetwork:
        driver: bridge
