---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mediawiki
  name: mediawiki_pod_a
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mediawiki
  template:
    metadata:
      labels:
        network/wikinetwork: "true"
        service: mediawiki
    spec:
      containers:
      - image: 741856792944.dkr.ecr.ap-south-1.amazonaws.com/bhanu-mediawiki-repo:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "400Mi"
            cpu: "500m"
        imagePullPolicy: Always
        name: mediawiki
        ports:
        - containerPort: 80
        volumeMounts:
          - name: mnt
            mountPath: /var/www/html/mediawiki/docs/
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: mnt
          configMap:
            name: samplecsvfile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mediawiki
  name: mediawiki_pod_b
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mediawiki
  template:
    metadata:
      labels:
        network/wikinetwork: "true"
        service: mediawiki
    spec:
      containers:
      - image: 741856792944.dkr.ecr.ap-south-1.amazonaws.com/bhanu-mediawiki-repo:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        imagePullPolicy: Always
        name: mediawiki
        ports:
        - containerPort: 80
        volumeMounts:
          - name: mnt
            mountPath: /var/www/html/mediawiki/docs/
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: mnt
          configMap:
            name: samplecsvfile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mediawiki
  name: mediawiki_pod_c
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mediawiki
  template:
    metadata:
      labels:
        network/wikinetwork: "true"
        service: mediawiki
    spec:
      containers:
      - image: 741856792944.dkr.ecr.ap-south-1.amazonaws.com/bhanu-mediawiki-repo:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "400Mi"
            cpu: "500m"
        imagePullPolicy: Always
        name: mediawiki
        ports:
        - containerPort: 80
        volumeMounts:
          - name: mnt
            mountPath: /var/www/html/mediawiki/docs/
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: mnt
          configMap:
            name: samplecsvfile
