---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: db
  name: db
spec:
  ports:
  - name: "33060"
    port: 33060
    targetPort: 3306
  selector:
    service: db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: mediawiki
  name: mediawiki
spec:
  type: LoadBalancer
  ports:
  - name: "8000"
    port: 8000
    targetPort: 80
  selector:
    service: mediawiki
