---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: db
  name: db
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    service: db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: mediawiki
  name: mediawiki
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    service: mediawiki
